### ISSUE TITLE
How can I change checkbox style?

### ISSUE THREAD

**Issue by ChintanRathod** [fferegrino/Forms.Checkbox#2]
This library is working fine, but when there is white background, checkbox are not visible. Is there any way to change style of checkbox? 
I also want to set disabled and checked images as per need. 

![checkbox_checked](https://cloud.githubusercontent.com/assets/4371780/16218728/14402dd4-379e-11e6-8f5b-b37395e98b52.PNG)
![checkbox_not_checked](https://cloud.githubusercontent.com/assets/4371780/16218731/18532570-379e-11e6-8539-885e9df3000f.PNG)

**Comment by fferegrino** [comment]
Hi.

Currently there is no way of changing the color for the checkbox on Android, yet, you can achieve it with Android themes

Are you familiar with Android themes? you should have a look at them:

https://navaneethant.wordpress.com/2013/10/05/change-the-default-checkbox-style-in-android/
http://stackoverflow.com/questions/10135499/android-checkbox-style

As of today, the [Android's CheckboxRenderer](https://github.com/messier16/Forms.Checkbox/blob/master/Droid/CheckboxRenderer.cs) just creates an Android.Widget.Checkbox which can be themed via the Theming mechanism in Android.

I hope this helps. If not, let me know. I also suggest you to move over to my new [Forms.Controls package](https://github.com/messier16/Forms.Controls#formscontrols) (it contains this Checkbox), as this (Forms.Checkbox) will stop receiving updates soon.

**Comment by ChintanRathod** [comment]
OK. Let me try with your solution. :)

**Comment by trushitsyx** [comment]
How to do same with xamarin forms ?

**Comment by fferegrino** [comment]
@trushitsyx actually, that IS the way to do it in Xamarin.Forms, as this plugin is only for Xamarin.Forms.

**Comment by fferegrino** [comment]
I'll close this issue as the original question & the latest one has already been answered :)
