### ISSUE TITLE
There is no CheckedChanged event in the CheckBox if getting the package through References

### ISSUE THREAD

**Issue by pvhd** [fferegrino/Forms.Checkbox#5]
I couldn't use the CheckedChanged event because it's missing from the package. I also noticed that the versions for iOS and Android are different if I manually add it from the references in each project.

When I add this library to the Android project, there are several errors happened in the Resource.Designer.cs, for example:
global::Messier16.Forms.Droid.Controls.Resource.Attribute.mediaRouteSettingsDrawable = global::QSRMobileCounting.Droid.Resource.Attribute.mediaRouteSettingsDrawable;

Do you know why this happens?

**Comment by fferegrino** [comment]
Not sure I understand the first question, mainly because you are not supposed to add manually references to this library, I developed it to be NuGet installable only.

As for the second, can you please clean upload a screenshot of the errors appearing?

**Comment by pvhd** [comment]
The error happened when I manually added the reference, so you don't need to worry about it anymore. Thanks.
