### ISSUE TITLE
.NET Standard

### ISSUE THREAD

**Issue by nodoid** [fferegrino/Forms.Checkbox#7]
Hi,

Any chance of a version which works with .NET Standard?

**Comment by fferegrino** [comment]
Please see [https://github.com/messier16/Forms.Controls](https://github.com/messier16/Forms.Controls), hope that's useful for you.

**Comment by nodoid** [comment]
Package Messier16.Forms.Controls 2.2.0 is not compatible with netstandard1.5 (.NETStandard,Version=v1.5). Package Messier16.Forms.Controls 2.2.0 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - portable-monoandroid10+monotouch10+net45+uap10+win8+wp8+wpa81+xamarinios10 (.NETPortable,Version=v0.0,Profile=net45+wp8+win8+wpa81+MonoAndroid10+MonoTouch10+Xamarin.iOS10+UAP10)
  - uap10 (UAP,Version=v1.0)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)

Not sure....
